(defun areaRectangulo()
    (princ "Dame la longitud de la base: ")
    (setq num1 (read))
    (princ "Dame la longitud de uno de sus lados: ")
    (setq num2 (read))
    (setq resultado (* num1 num2))
)