(defun sumaNumero()
    (princ "Dame el primer numero: ")
    (setq num1 (read))
    (princ "Dame el segundo numero: ")
    (setq num2 (read))
    (setq resultado (+ num1 num2))
    ;(write resultado)
)